name: hello

on:
  push:
    branches: [main]

jobs:

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Current date and time
        run: date

      - name: Print branch name 
        run: echo "The triggering branch name is ${{ github.ref_name }}"

      - name: List the file
        run: git ls-files

      - name: Print the runner operating system
        run: echo "The runner OS is ${{ runner.os }}"

      - name: Fail step
        run: exit 1

      # This is test comment for debuging
